name: Deploy Vite App to AWS S3

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Use Node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: pnpm

      
      - name: Install dependencies 📦️
        run: pnpm install --prefer-frozen-lockfile

      - name: Build 🔨
        run: pnpm build

      - name: Copy sitemap.xml and robots.txt into dist/ 📄
        run: |
          cp sitemap.xml dist/ || echo "No sitemap.xml found"
          cp robots.txt dist/ || echo "No robots.txt found"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy dist/ to S3 bucket
        run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache (optional)
      
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
